In [1]:
import numpy as np
import pandas as pd

from sklearn.feature_selection import mutual_info_classif
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

import warnings
from pandas.errors import PerformanceWarning

warnings.filterwarnings('ignore', category=PerformanceWarning)
pd.set_option('display.max_columns', None)

In [2]:
#1. Building the test set

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
solution = pd.read_csv("solution.csv")

In [3]:
ID_COL = "MSISDN"

CRM_COLS = [c for c in train.columns if c.startswith("CRM")]
BIL_COLS = [c for c in train.columns if c.startswith("BIL")]

In [4]:
solution.columns

Index(['MSISDN', 'Bill_Conf'], dtype='object')

In [5]:
SOLUTION_STRING_COL = "Bill_Conf"

test = test.merge(
    solution[[ID_COL, SOLUTION_STRING_COL]],
    on=ID_COL,
    how="left"
)

In [6]:
test.head()

,MSISDN,CRM_BUSINESS_LINE_ORIG_Mobile,CRM_1519_PACK,CRM_1521_PACK,CRM_1522_PACK,CRM_1523_PACK,CRM_1524_PACK,CRM_1525_PACK,CRM_1526_PACK,CRM_1527_PACK,CRM_1528_PACK,CRM_1529_PACK,CRM_1530_PACK,CRM_1532_PACK,CRM_1533_PACK,CRM_1534_PACK,CRM_1536_PACK,CRM_1537_PACK,CRM_1538_PACK,CRM_1539_PACK,CRM_1540_PACK,CRM_1541_PACK,CRM_1542_PACK,CRM_1543_PACK,CRM_1545_PACK,CRM_1546_PACK,CRM_1547_PACK,CRM_1548_PACK,CRM_1549_PACK,CRM_1550_PACK,CRM_1551_PACK,CRM_1552_PACK,CRM_1553_PACK,CRM_1554_PACK,CRM_1555_PACK,CRM_1556_PACK,CRM_1557_PACK,CRM_1558_PACK,CRM_1559_PACK,CRM_1560_PACK,CRM_1562_PACK,CRM_1563_PACK,CRM_1564_PACK,CRM_1565_PACK,CRM_1566_PACK,CRM_1567_PACK,CRM_1568_PACK,CRM_1569_PACK,CRM_1570_PACK,CRM_1571_PACK,CRM_1573_PACK,CRM_1575_PACK,CRM_1576_PACK,CRM_1577_PACK,CRM_1578_PACK,CRM_1579_PACK,CRM_1581_PACK,CRM_1582_PACK,CRM_1583_PACK,CRM_1584_PACK,CRM_1585_PACK,CRM_1586_PACK,CRM_1587_PACK,CRM_1588_PACK,CRM_1589_PACK,CRM_1590_PACK,CRM_1591_PACK,CRM_1592_PACK,CRM_1593_PACK,CRM_1594_PACK,CRM_1595_PACK,CRM_1596_PACK,CRM_1598_PACK,CRM_1599_PACK,CRM_1601_PACK,CRM_1602_PACK,CRM_1603_PACK,CRM_1604_PACK,CRM_1605_PACK,CRM_1606_PACK,CRM_1608_PACK,CRM_1609_PACK,CRM_1612_PACK,CRM_1613_PACK,CRM_1614_PACK,CRM_1615_PACK,CRM_1616_PACK,CRM_1617_PACK,CRM_1619_PACK,CRM_1623_PACK,CRM_1625_PACK,CRM_1626_PACK,CRM_1627_PACK,CRM_1629_PACK,CRM_1630_PACK,CRM_1631_PACK,CRM_1635_PACK,CRM_1638_PACK,CRM_1639_PACK,CRM_1640_PACK,CRM_1641_PACK,CRM_1642_PACK,CRM_1643_PACK,CRM_1644_PACK,CRM_1645_PACK,CRM_1646_PACK,CRM_1647_PACK,CRM_1648_PACK,CRM_1653_PACK,CRM_1654_PACK,CRM_1658_PACK,CRM_1661_PACK,CRM_1662_PACK,CRM_1664_PACK,CRM_1665_PACK,CRM_1666_PACK,CRM_1668_PACK,CRM_1669_PACK,CRM_1670_PACK,CRM_1671_PACK,CRM_1675_PACK,CRM_1676_PACK,CRM_1678_PACK,CRM_1680_PACK,CRM_1683_PACK,CRM_1689_PACK,CRM_1690_PACK,CRM_1692_PACK,CRM_1702_PACK,CRM_1704_PACK,CRM_1705_PACK,CRM_1708_PACK,CRM_1709_PACK,CRM_1710_PACK,CRM_1715_PACK,CRM_2076_PACK,CRM_2077_PACK,CRM_2078_PACK,CRM_2079_PACK,CRM_2080_PACK,CRM_2081_PACK,CRM_2082_PACK,CRM_2083_PACK,CRM_2084_PACK,CRM_2085_PACK,CRM_2086_PACK,CRM_2087_PACK,CRM_2088_PACK,CRM_2089_PACK,CRM_2090_PACK,CRM_2091_PACK,CRM_2092_PACK,CRM_2093_PACK,CRM_2094_PACK,CRM_2095_PACK,CRM_2096_PACK,CRM_2097_PACK,CRM_2099_PACK,CRM_2100_PACK,CRM_2101_PACK,CRM_2102_PACK,CRM_2103_PACK,CRM_2104_PACK,CRM_2105_PACK,CRM_2106_PACK,CRM_2107_PACK,CRM_2109_PACK,CRM_2111_PACK,CRM_2112_PACK,CRM_2113_PACK,CRM_2114_PACK,CRM_2115_PACK,CRM_2116_PACK,CRM_2117_PACK,CRM_2118_PACK,CRM_2121_PACK,CRM_2123_PACK,CRM_2126_PACK,CRM_2127_PACK,CRM_2128_PACK,CRM_2129_PACK,CRM_2130_PACK,CRM_2132_PACK,CRM_2134_PACK,CRM_2135_PACK,CRM_2137_PACK,CRM_2138_PACK,CRM_2139_PACK,CRM_2140_PACK,CRM_SUBSCRIBER_TYPE_ORIG_0,CRM_SUBSCRIBER_TYPE_ORIG_Postpaid,CRM_SUBSCRIBER_TYPE_ORIG_Prepaid,CRM_SUBSCRIBER_STATUS_ORIG_0,CRM_SUBSCRIBER_STATUS_ORIG_Active,CRM_SUBSCRIBER_STATUS_ORIG_Barring,CRM_SUBSCRIBER_STATUS_ORIG_Block_1_Way,CRM_SUBSCRIBER_STATUS_ORIG_Block_2_Way,CRM_SUBSCRIBER_STATUS_ORIG_Deactive,CRM_SUBSCRIBER_STATUS_ORIG_Idle,CRM_SUBSCRIBER_STATUS_ORIG_Pre_Active,CRM_SUBSCRIBER_STATUS_ORIG_Pre_Deactivated,CRM_SUBSCRIBER_STATUS_ORIG_Pre_Expired,CRM_SUBSCRIBER_STATUS_ORIG_Suspend,CRM_2141_PACK,CRM_2142_PACK,CRM_2143_PACK,CRM_2146_PACK,CRM_2147_PACK,CRM_2148_PACK,CRM_2149_PACK,CRM_2153_PACK,CRM_2154_PACK,CRM_2155_PACK,CRM_2161_PACK,CRM_1531_PACK,CRM_1561_PACK,CRM_1597_PACK,CRM_1600_PACK,CRM_1607_PACK,CRM_1610_PACK,CRM_1611_PACK,CRM_1618_PACK,CRM_1620_PACK,CRM_1621_PACK,CRM_1622_PACK,CRM_1624_PACK,CRM_1633_PACK,CRM_1636_PACK,CRM_1637_PACK,CRM_1649_PACK,CRM_1650_PACK,CRM_1651_PACK,CRM_1652_PACK,CRM_1655_PACK,CRM_1656_PACK,CRM_1657_PACK,CRM_1660_PACK,CRM_1663_PACK,CRM_1667_PACK,CRM_1672_PACK,CRM_1673_PACK,CRM_1674_PACK,CRM_1677_PACK,CRM_1679_PACK,CRM_1682_PACK,CRM_1684_PACK,CRM_1685_PACK,CRM_1686_PACK,CRM_1687_PACK,CRM_1688_PACK,CRM_1691_PACK,CRM_1693_PACK,CRM_1694_PACK,CRM_1695_PACK,CRM_1696_PACK,CRM_1697_PACK,CRM_1698_PACK,CRM_1699_PACK,CRM_1700_PACK,CRM_1701_PACK,CRM_1706_PACK,CRM_1712_PACK,CRM_1714_PACK,CRM_1717_PACK,CRM_1718_PACK,CRM_1719_PACK,CRM_1720_PACK,CRM_1721_PACK,CRM_1722_PACK,CRM_1723_PACK,CRM_1724_PACK,CRM_1725_PACK,CRM_1726_PACK,CRM_1727_PACK,CRM_1730_PACK,CRM_1732_PACK,CRM_1734_PACK,CRM_1735_PACK,CRM_1737_PACK,CRM_1738_PACK,CRM_1739_PACK,CRM_1740_PACK,CRM_1741_PACK,CRM_1742_PACK,CRM_1743_PACK,CRM_1744_PACK,CRM_1745_PACK,CRM_1746_PACK,CRM_1748_PACK,CRM_1749_PACK,CRM_1751_PACK,CRM_1752_PACK,CRM_1753_PACK,CRM_1754_PACK,CRM_1755_PACK,CRM_1758_PACK,CRM_1759_PACK,CRM_1760_PACK,CRM_1761_PACK,CRM_1762_PACK,CRM_1763_PACK,CRM_1765_PACK,CRM_1767_PACK,CRM_1769_PACK,CRM_1770_PACK,CRM_1772_PACK,CRM_1773_PACK,CRM_1775_PACK,CRM_1776_PACK,CRM_1777_PACK,CRM_1778_PACK,CRM_1779_PACK,CRM_1780_PACK,CRM_1781_PACK,CRM_1783_PACK,CRM_1784_PACK,CRM_1785_PACK,CRM_1786_PACK,CRM_1790_PACK,CRM_1791_PACK,CRM_1794_PACK,CRM_1797_PACK,CRM_1798_PACK,CRM_1799_PACK,CRM_1803_PACK,CRM_1804_PACK,CRM_1805_PACK,CRM_1806_PACK,CRM_1807_PACK,CRM_1808_PACK,CRM_1809_PACK,CRM_1811_PACK,CRM_1812_PACK,CRM_1813_PACK,CRM_1815_PACK,CRM_1816_PACK,CRM_1817_PACK,CRM_1818_PACK,CRM_1820_PACK,CRM_1824_PACK,CRM_1825_PACK,CRM_1826_PACK,CRM_1827_PACK,CRM_1828_PACK,CRM_1832_PACK,CRM_1833_PACK,CRM_1836_PACK,CRM_1842_PACK,CRM_1843_PACK,CRM_1844_PACK,CRM_1845_PACK,CRM_1848_PACK,CRM_1849_PACK,CRM_1851_PACK,CRM_1865_PACK,CRM_1874_PACK,CRM_1875_PACK,CRM_1876_PACK,CRM_1877_PACK,CRM_1878_PACK,CRM_1881_PACK,CRM_2098_PACK,CRM_2108_PACK,CRM_2110_PACK,CRM_2119_PACK,CRM_2120_PACK,CRM_2122_PACK,CRM_2124_PACK,CRM_2125_PACK,CRM_2133_PACK,CRM_2136_PACK,CRM_2144_PACK,CRM_2145_PACK,CRM_2150_PACK,CRM_2151_PACK,CRM_2152_PACK,CRM_2156_PACK,CRM_2157_PACK,CRM_2158_PACK,CRM_2159_PACK,CRM_2160_PACK,CRM_2163_PACK,CRM_2165_PACK,CRM_2166_PACK,CRM_2167_PACK,CRM_2168_PACK,CRM_2169_PACK,CRM_2170_PACK,CRM_2171_PACK,CRM_2173_PACK,CRM_2174_PACK,CRM_2175_PACK,CRM_2177_PACK,CRM_2178_PACK,CRM_2179_PACK,CRM_2180_PACK,CRM_2182_PACK,CRM_2184_PACK,CRM_2185_PACK,CRM_2186_PACK,CRM_2190_PACK,CRM_2192_PACK,CRM_2193_PACK,CRM_2195_PACK,CRM_2197_PACK,CRM_2201_PACK,CRM_2205_PACK,CRM_2212_PACK,CRM_2219_PACK,CRM_2220_PACK,CRM_1634_PACK,CRM_1659_PACK,CRM_1703_PACK,CRM_1707_PACK,CRM_1711_PACK,CRM_1713_PACK,CRM_1716_PACK,CRM_1728_PACK,CRM_1729_PACK,CRM_1731_PACK,CRM_1733_PACK,CRM_1736_PACK,CRM_1747_PACK,CRM_1750_PACK,CRM_1756_PACK,CRM_1757_PACK,CRM_1764_PACK,CRM_1766_PACK,CRM_1768_PACK,CRM_1771_PACK,CRM_1774_PACK,CRM_1782_PACK,CRM_1787_PACK,CRM_1788_PACK,CRM_1789_PACK,CRM_1792_PACK,CRM_1793_PACK,CRM_1795_PACK,CRM_1796_PACK,CRM_1800_PACK,CRM_1801_PACK,CRM_1802_PACK,CRM_1810_PACK,CRM_1814_PACK,CRM_1819_PACK,CRM_1821_PACK,CRM_1822_PACK,CRM_1823_PACK,CRM_1829_PACK,CRM_1830_PACK,CRM_1834_PACK,CRM_1835_PACK,CRM_1840_PACK,CRM_1841_PACK,CRM_1846_PACK,CRM_1847_PACK,CRM_1850_PACK,CRM_1852_PACK,CRM_1853_PACK,CRM_1854_PACK,CRM_1855_PACK,CRM_1856_PACK,CRM_1857_PACK,CRM_1858_PACK,CRM_1859_PACK,CRM_1860_PACK,CRM_1861_PACK,CRM_1862_PACK,CRM_1863_PACK,CRM_1864_PACK,CRM_1866_PACK,CRM_1867_PACK,CRM_1868_PACK,CRM_1869_PACK,CRM_1870_PACK,CRM_1871_PACK,CRM_1873_PACK,CRM_1879_PACK,CRM_1880_PACK,CRM_1883_PACK,CRM_1884_PACK,CRM_1885_PACK,CRM_1886_PACK,CRM_1887_PACK,CRM_1888_PACK,CRM_1889_PACK,CRM_1890_PACK,CRM_1892_PACK,CRM_1893_PACK,CRM_1894_PACK,CRM_1895_PACK,CRM_1896_PACK,CRM_1899_PACK,CRM_1900_PACK,CRM_1901_PACK,CRM_1902_PACK,CRM_1903_PACK,CRM_1905_PACK,CRM_1906_PACK,CRM_1907_PACK,CRM_1908_PACK,CRM_1909_PACK,CRM_1911_PACK,CRM_1912_PACK,CRM_1917_PACK,CRM_1926_PACK,CRM_1933_PACK,CRM_1941_PACK,CRM_1943_PACK,CRM_1944_PACK,CRM_1946_PACK,CRM_1949_PACK,CRM_1950_PACK,CRM_1952_PACK,CRM_1953_PACK,CRM_1954_PACK,CRM_1956_PACK,CRM_1961_PACK,CRM_1962_PACK,CRM_1963_PACK,CRM_1964_PACK,CRM_1966_PACK,CRM_2061_PACK,CRM_2063_PACK,CRM_2066_PACK,CRM_2068_PACK,CRM_2069_PACK,CRM_2070_PACK,CRM_2071_PACK,CRM_2072_PACK,CRM_2073_PACK,CRM_2074_PACK,CRM_2075_PACK,CRM_2131_PACK,CRM_2176_PACK,CRM_2181_PACK,CRM_2183_PACK,CRM_2187_PACK,CRM_2188_PACK,CRM_2191_PACK,CRM_2194_PACK,CRM_2196_PACK,CRM_2198_PACK,CRM_2199_PACK,CRM_2200_PACK,CRM_2203_PACK,CRM_2204_PACK,CRM_2206_PACK,CRM_2207_PACK,CRM_2208_PACK,CRM_2210_PACK,CRM_2213_PACK,CRM_2214_PACK,CRM_2216_PACK,CRM_2218_PACK,CRM_2221_PACK,CRM_2222_PACK,CRM_2223_PACK,CRM_2224_PACK,CRM_2225_PACK,CRM_2226_PACK,CRM_2228_PACK,CRM_2229_PACK,CRM_2230_PACK,CRM_2231_PACK,CRM_2234_PACK,CRM_2235_PACK,CRM_2236_PACK,CRM_2237_PACK,CRM_2238_PACK,CRM_2239_PACK,CRM_2240_PACK,CRM_2241_PACK,CRM_2242_PACK,CRM_2243_PACK,CRM_2244_PACK,CRM_2245_PACK,CRM_2246_PACK,CRM_2247_PACK,CRM_2248_PACK,CRM_2249_PACK,CRM_2250_PACK,CRM_2251_PACK,CRM_2253_PACK,CRM_2254_PACK,CRM_2256_PACK,CRM_2257_PACK,CRM_2259_PACK,CRM_2262_PACK,CRM_2263_PACK,CRM_2265_PACK,CRM_2267_PACK,CRM_2271_PACK,CRM_2276_PACK,CRM_2283_PACK,CRM_2287_PACK,CRM_2290_PACK,CRM_2296_PACK,CRM_2299_PACK,CRM_2301_PACK,CRM_2302_PACK,CRM_2307_PACK,CRM_2309_PACK,CRM_2317_PACK,CRM_1632_PACK,CRM_1831_PACK,CRM_1839_PACK,CRM_1872_PACK,CRM_1882_PACK,CRM_1891_PACK,CRM_1897_PACK,CRM_1904_PACK,CRM_1910_PACK,CRM_1930_PACK,CRM_1931_PACK,CRM_1932_PACK,CRM_1951_PACK,CRM_1959_PACK,CRM_1968_PACK,CRM_1969_PACK,CRM_2062_PACK,CRM_2064_PACK,CRM_2065_PACK,CRM_2067_PACK,CRM_2164_PACK,CRM_2189_PACK,CRM_2209_PACK,CRM_2211_PACK,CRM_2215_PACK,CRM_2227_PACK,CRM_2232_PACK,CRM_2233_PACK,CRM_2252_PACK,CRM_2255_PACK,CRM_2258_PACK,CRM_2266_PACK,CRM_2268_PACK,CRM_2269_PACK,CRM_2270_PACK,CRM_2272_PACK,CRM_2273_PACK,CRM_2274_PACK,CRM_2275_PACK,CRM_2277_PACK,CRM_2278_PACK,CRM_2279_PACK,CRM_2280_PACK,CRM_2281_PACK,CRM_2282_PACK,CRM_2284_PACK,CRM_2285_PACK,CRM_2286_PACK,CRM_2288_PACK,CRM_2289_PACK,CRM_2291_PACK,CRM_2292_PACK,CRM_2293_PACK,CRM_2294_PACK,CRM_2297_PACK,CRM_2298_PACK,CRM_2300_PACK,CRM_2303_PACK,CRM_2304_PACK,CRM_2305_PACK,CRM_2306_PACK,CRM_2308_PACK,CRM_2311_PACK,CRM_2312_PACK,CRM_2313_PACK,CRM_2314_PACK,CRM_2315_PACK,CRM_2316_PACK,CRM_2319_PACK,CRM_2320_PACK,CRM_2321_PACK,CRM_2322_PACK,CRM_2323_PACK,CRM_2324_PACK,CRM_2325_PACK,CRM_2326_PACK,CRM_2327_PACK,CRM_2328_PACK,CRM_2329_PACK,CRM_2330_PACK,CRM_2331_PACK,CRM_2332_PACK,CRM_2333_PACK,CRM_2335_PACK,CRM_2336_PACK,CRM_2337_PACK,CRM_2338_PACK,CRM_2339_PACK,CRM_2340_PACK,CRM_2341_PACK,CRM_2342_PACK,CRM_2343_PACK,CRM_2344_PACK,CRM_2345_PACK,CRM_2346_PACK,CRM_2347_PACK,CRM_2348_PACK,CRM_2349_PACK,CRM_2351_PACK,CRM_2352_PACK,CRM_2353_PACK,CRM_2354_PACK,CRM_2355_PACK,CRM_2356_PACK,CRM_2357_PACK,CRM_2358_PACK,CRM_2359_PACK,CRM_2360_PACK,CRM_2361_PACK,CRM_2362_PACK,CRM_2363_PACK,CRM_2364_PACK,CRM_2365_PACK,CRM_2366_PACK,CRM_2367_PACK,CRM_2368_PACK,CRM_2369_PACK,CRM_2370_PACK,CRM_2371_PACK,CRM_2372_PACK,CRM_2373_PACK,CRM_2374_PACK,CRM_2375_PACK,CRM_2376_PACK,CRM_2377_PACK,CRM_2378_PACK,CRM_2379_PACK,CRM_2380_PACK,CRM_2381_PACK,CRM_2382_PACK,CRM_2383_PACK,CRM_2385_PACK,CRM_2387_PACK,CRM_2388_PACK,CRM_2389_PACK,CRM_2391_PACK,CRM_2392_PACK,CRM_2394_PACK,CRM_2395_PACK,CRM_2396_PACK,CRM_2397_PACK,CRM_2398_PACK,Bill_Conf
0,db67b03cf9fb8ea96077cd34c7a28139,1,0,1,1,1,0,0,1,1,1,1,0,1,1,0,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000000000000000000000000000000000000000000000...
1,2ac0d310d5cf1a96587af614d37b8b54,1,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000000000100000000000000000000100000000000000...
2,a8f289fbd263794ac74059a18c1d10a5,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1100000110111100000000000000000000010000000000...
3,5a53a1c85ccc7e794c90c75b75b8d3cb,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1110000110111010100000000000000000010000000000...
4,484b400226b8894377e12204219283fc,1,0,0,0,0,0,0,0,0,1,1,0,1,1,0,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000000000000000000000000000000000000000000000...

In [7]:
solutions = test['Bill_Conf'].apply(list).apply(pd.Series).astype(int)

test = pd.concat([test, solutions], axis=1)

In [8]:
test.head()

,MSISDN,CRM_BUSINESS_LINE_ORIG_Mobile,CRM_1519_PACK,CRM_1521_PACK,CRM_1522_PACK,CRM_1523_PACK,CRM_1524_PACK,CRM_1525_PACK,CRM_1526_PACK,CRM_1527_PACK,CRM_1528_PACK,CRM_1529_PACK,CRM_1530_PACK,CRM_1532_PACK,CRM_1533_PACK,CRM_1534_PACK,CRM_1536_PACK,CRM_1537_PACK,CRM_1538_PACK,CRM_1539_PACK,CRM_1540_PACK,CRM_1541_PACK,CRM_1542_PACK,CRM_1543_PACK,CRM_1545_PACK,CRM_1546_PACK,CRM_1547_PACK,CRM_1548_PACK,CRM_1549_PACK,CRM_1550_PACK,CRM_1551_PACK,CRM_1552_PACK,CRM_1553_PACK,CRM_1554_PACK,CRM_1555_PACK,CRM_1556_PACK,CRM_1557_PACK,CRM_1558_PACK,CRM_1559_PACK,CRM_1560_PACK,CRM_1562_PACK,CRM_1563_PACK,CRM_1564_PACK,CRM_1565_PACK,CRM_1566_PACK,CRM_1567_PACK,CRM_1568_PACK,CRM_1569_PACK,CRM_1570_PACK,CRM_1571_PACK,CRM_1573_PACK,CRM_1575_PACK,CRM_1576_PACK,CRM_1577_PACK,CRM_1578_PACK,CRM_1579_PACK,CRM_1581_PACK,CRM_1582_PACK,CRM_1583_PACK,CRM_1584_PACK,CRM_1585_PACK,CRM_1586_PACK,CRM_1587_PACK,CRM_1588_PACK,CRM_1589_PACK,CRM_1590_PACK,CRM_1591_PACK,CRM_1592_PACK,CRM_1593_PACK,CRM_1594_PACK,CRM_1595_PACK,CRM_1596_PACK,CRM_1598_PACK,CRM_1599_PACK,CRM_1601_PACK,CRM_1602_PACK,CRM_1603_PACK,CRM_1604_PACK,CRM_1605_PACK,CRM_1606_PACK,CRM_1608_PACK,CRM_1609_PACK,CRM_1612_PACK,CRM_1613_PACK,CRM_1614_PACK,CRM_1615_PACK,CRM_1616_PACK,CRM_1617_PACK,CRM_1619_PACK,CRM_1623_PACK,CRM_1625_PACK,CRM_1626_PACK,CRM_1627_PACK,CRM_1629_PACK,CRM_1630_PACK,CRM_1631_PACK,CRM_1635_PACK,CRM_1638_PACK,CRM_1639_PACK,CRM_1640_PACK,CRM_1641_PACK,CRM_1642_PACK,CRM_1643_PACK,CRM_1644_PACK,CRM_1645_PACK,CRM_1646_PACK,CRM_1647_PACK,CRM_1648_PACK,CRM_1653_PACK,CRM_1654_PACK,CRM_1658_PACK,CRM_1661_PACK,CRM_1662_PACK,CRM_1664_PACK,CRM_1665_PACK,CRM_1666_PACK,CRM_1668_PACK,CRM_1669_PACK,CRM_1670_PACK,CRM_1671_PACK,CRM_1675_PACK,CRM_1676_PACK,CRM_1678_PACK,CRM_1680_PACK,CRM_1683_PACK,CRM_1689_PACK,CRM_1690_PACK,CRM_1692_PACK,CRM_1702_PACK,CRM_1704_PACK,CRM_1705_PACK,CRM_1708_PACK,CRM_1709_PACK,CRM_1710_PACK,CRM_1715_PACK,CRM_2076_PACK,CRM_2077_PACK,CRM_2078_PACK,CRM_2079_PACK,CRM_2080_PACK,CRM_2081_PACK,CRM_2082_PACK,CRM_2083_PACK,CRM_2084_PACK,CRM_2085_PACK,CRM_2086_PACK,CRM_2087_PACK,CRM_2088_PACK,CRM_2089_PACK,CRM_2090_PACK,CRM_2091_PACK,CRM_2092_PACK,CRM_2093_PACK,CRM_2094_PACK,CRM_2095_PACK,CRM_2096_PACK,CRM_2097_PACK,CRM_2099_PACK,CRM_2100_PACK,CRM_2101_PACK,CRM_2102_PACK,CRM_2103_PACK,CRM_2104_PACK,CRM_2105_PACK,CRM_2106_PACK,CRM_2107_PACK,CRM_2109_PACK,CRM_2111_PACK,CRM_2112_PACK,CRM_2113_PACK,CRM_2114_PACK,CRM_2115_PACK,CRM_2116_PACK,CRM_2117_PACK,CRM_2118_PACK,CRM_2121_PACK,CRM_2123_PACK,CRM_2126_PACK,CRM_2127_PACK,CRM_2128_PACK,CRM_2129_PACK,CRM_2130_PACK,CRM_2132_PACK,CRM_2134_PACK,CRM_2135_PACK,CRM_2137_PACK,CRM_2138_PACK,CRM_2139_PACK,CRM_2140_PACK,CRM_SUBSCRIBER_TYPE_ORIG_0,CRM_SUBSCRIBER_TYPE_ORIG_Postpaid,CRM_SUBSCRIBER_TYPE_ORIG_Prepaid,CRM_SUBSCRIBER_STATUS_ORIG_0,CRM_SUBSCRIBER_STATUS_ORIG_Active,CRM_SUBSCRIBER_STATUS_ORIG_Barring,CRM_SUBSCRIBER_STATUS_ORIG_Block_1_Way,CRM_SUBSCRIBER_STATUS_ORIG_Block_2_Way,CRM_SUBSCRIBER_STATUS_ORIG_Deactive,CRM_SUBSCRIBER_STATUS_ORIG_Idle,CRM_SUBSCRIBER_STATUS_ORIG_Pre_Active,CRM_SUBSCRIBER_STATUS_ORIG_Pre_Deactivated,CRM_SUBSCRIBER_STATUS_ORIG_Pre_Expired,CRM_SUBSCRIBER_STATUS_ORIG_Suspend,CRM_2141_PACK,CRM_2142_PACK,CRM_2143_PACK,CRM_2146_PACK,CRM_2147_PACK,CRM_2148_PACK,CRM_2149_PACK,CRM_2153_PACK,CRM_2154_PACK,CRM_2155_PACK,CRM_2161_PACK,CRM_1531_PACK,CRM_1561_PACK,CRM_1597_PACK,CRM_1600_PACK,CRM_1607_PACK,CRM_1610_PACK,CRM_1611_PACK,CRM_1618_PACK,CRM_1620_PACK,CRM_1621_PACK,CRM_1622_PACK,CRM_1624_PACK,CRM_1633_PACK,CRM_1636_PACK,CRM_1637_PACK,CRM_1649_PACK,CRM_1650_PACK,CRM_1651_PACK,CRM_1652_PACK,CRM_1655_PACK,CRM_1656_PACK,CRM_1657_PACK,CRM_1660_PACK,CRM_1663_PACK,CRM_1667_PACK,CRM_1672_PACK,CRM_1673_PACK,CRM_1674_PACK,CRM_1677_PACK,CRM_1679_PACK,CRM_1682_PACK,CRM_1684_PACK,CRM_1685_PACK,CRM_1686_PACK,CRM_1687_PACK,CRM_1688_PACK,CRM_1691_PACK,CRM_1693_PACK,CRM_1694_PACK,CRM_1695_PACK,CRM_1696_PACK,CRM_1697_PACK,CRM_1698_PACK,CRM_1699_PACK,CRM_1700_PACK,CRM_1701_PACK,CRM_1706_PACK,CRM_1712_PACK,CRM_1714_PACK,CRM_1717_PACK,CRM_1718_PACK,CRM_1719_PACK,CRM_1720_PACK,CRM_1721_PACK,CRM_1722_PACK,CRM_1723_PACK,CRM_1724_PACK,CRM_1725_PACK,CRM_1726_PACK,CRM_1727_PACK,CRM_1730_PACK,CRM_1732_PACK,CRM_1734_PACK,CRM_1735_PACK,CRM_1737_PACK,CRM_1738_PACK,CRM_1739_PACK,CRM_1740_PACK,CRM_1741_PACK,CRM_1742_PACK,CRM_1743_PACK,CRM_1744_PACK,CRM_1745_PACK,CRM_1746_PACK,CRM_1748_PACK,CRM_1749_PACK,CRM_1751_PACK,CRM_1752_PACK,CRM_1753_PACK,CRM_1754_PACK,CRM_1755_PACK,CRM_1758_PACK,CRM_1759_PACK,CRM_1760_PACK,CRM_1761_PACK,CRM_1762_PACK,CRM_1763_PACK,CRM_1765_PACK,CRM_1767_PACK,CRM_1769_PACK,CRM_1770_PACK,CRM_1772_PACK,CRM_1773_PACK,CRM_1775_PACK,CRM_1776_PACK,CRM_1777_PACK,CRM_1778_PACK,CRM_1779_PACK,CRM_1780_PACK,CRM_1781_PACK,CRM_1783_PACK,CRM_1784_PACK,CRM_1785_PACK,CRM_1786_PACK,CRM_1790_PACK,CRM_1791_PACK,CRM_1794_PACK,CRM_1797_PACK,CRM_1798_PACK,CRM_1799_PACK,CRM_1803_PACK,CRM_1804_PACK,CRM_1805_PACK,CRM_1806_PACK,CRM_1807_PACK,CRM_1808_PACK,CRM_1809_PACK,CRM_1811_PACK,CRM_1812_PACK,CRM_1813_PACK,CRM_1815_PACK,CRM_1816_PACK,CRM_1817_PACK,CRM_1818_PACK,CRM_1820_PACK,CRM_1824_PACK,CRM_1825_PACK,CRM_1826_PACK,CRM_1827_PACK,CRM_1828_PACK,CRM_1832_PACK,CRM_1833_PACK,CRM_1836_PACK,CRM_1842_PACK,CRM_1843_PACK,CRM_1844_PACK,CRM_1845_PACK,CRM_1848_PACK,CRM_1849_PACK,CRM_1851_PACK,CRM_1865_PACK,CRM_1874_PACK,CRM_1875_PACK,CRM_1876_PACK,CRM_1877_PACK,CRM_1878_PACK,CRM_1881_PACK,CRM_2098_PACK,CRM_2108_PACK,CRM_2110_PACK,CRM_2119_PACK,CRM_2120_PACK,CRM_2122_PACK,CRM_2124_PACK,CRM_2125_PACK,CRM_2133_PACK,CRM_2136_PACK,CRM_2144_PACK,CRM_2145_PACK,CRM_2150_PACK,CRM_2151_PACK,CRM_2152_PACK,CRM_2156_PACK,CRM_2157_PACK,CRM_2158_PACK,CRM_2159_PACK,CRM_2160_PACK,CRM_2163_PACK,CRM_2165_PACK,CRM_2166_PACK,CRM_2167_PACK,CRM_2168_PACK,CRM_2169_PACK,CRM_2170_PACK,CRM_2171_PACK,CRM_2173_PACK,CRM_2174_PACK,CRM_2175_PACK,CRM_2177_PACK,CRM_2178_PACK,CRM_2179_PACK,CRM_2180_PACK,CRM_2182_PACK,CRM_2184_PACK,CRM_2185_PACK,CRM_2186_PACK,CRM_2190_PACK,CRM_2192_PACK,CRM_2193_PACK,CRM_2195_PACK,CRM_2197_PACK,CRM_2201_PACK,CRM_2205_PACK,CRM_2212_PACK,CRM_2219_PACK,CRM_2220_PACK,CRM_1634_PACK,CRM_1659_PACK,CRM_1703_PACK,CRM_1707_PACK,CRM_1711_PACK,CRM_1713_PACK,CRM_1716_PACK,CRM_1728_PACK,CRM_1729_PACK,CRM_1731_PACK,CRM_1733_PACK,CRM_1736_PACK,CRM_1747_PACK,CRM_1750_PACK,CRM_1756_PACK,CRM_1757_PACK,CRM_1764_PACK,CRM_1766_PACK,CRM_1768_PACK,CRM_1771_PACK,CRM_1774_PACK,CRM_1782_PACK,CRM_1787_PACK,CRM_1788_PACK,CRM_1789_PACK,CRM_1792_PACK,CRM_1793_PACK,CRM_1795_PACK,CRM_1796_PACK,CRM_1800_PACK,CRM_1801_PACK,CRM_1802_PACK,CRM_1810_PACK,CRM_1814_PACK,CRM_1819_PACK,CRM_1821_PACK,CRM_1822_PACK,CRM_1823_PACK,CRM_1829_PACK,CRM_1830_PACK,CRM_1834_PACK,CRM_1835_PACK,CRM_1840_PACK,CRM_1841_PACK,CRM_1846_PACK,CRM_1847_PACK,CRM_1850_PACK,CRM_1852_PACK,CRM_1853_PACK,CRM_1854_PACK,CRM_1855_PACK,CRM_1856_PACK,CRM_1857_PACK,CRM_1858_PACK,CRM_1859_PACK,CRM_1860_PACK,CRM_1861_PACK,CRM_1862_PACK,CRM_1863_PACK,CRM_1864_PACK,CRM_1866_PACK,CRM_1867_PACK,CRM_1868_PACK,CRM_1869_PACK,CRM_1870_PACK,CRM_1871_PACK,CRM_1873_PACK,CRM_1879_PACK,CRM_1880_PACK,CRM_1883_PACK,CRM_1884_PACK,CRM_1885_PACK,CRM_1886_PACK,CRM_1887_PACK,CRM_1888_PACK,CRM_1889_PACK,CRM_1890_PACK,CRM_1892_PACK,CRM_1893_PACK,CRM_1894_PACK,CRM_1895_PACK,CRM_1896_PACK,CRM_1899_PACK,CRM_1900_PACK,CRM_1901_PACK,CRM_1902_PACK,CRM_1903_PACK,CRM_1905_PACK,CRM_1906_PACK,CRM_1907_PACK,CRM_1908_PACK,CRM_1909_PACK,CRM_1911_PACK,CRM_1912_PACK,CRM_1917_PACK,CRM_1926_PACK,CRM_1933_PACK,CRM_1941_PACK,CRM_1943_PACK,CRM_1944_PACK,CRM_1946_PACK,CRM_1949_PACK,CRM_1950_PACK,CRM_1952_PACK,CRM_1953_PACK,CRM_1954_PACK,CRM_1956_PACK,CRM_1961_PACK,CRM_1962_PACK,CRM_1963_PACK,CRM_1964_PACK,CRM_1966_PACK,CRM_2061_PACK,CRM_2063_PACK,CRM_2066_PACK,CRM_2068_PACK,CRM_2069_PACK,CRM_2070_PACK,CRM_2071_PACK,CRM_2072_PACK,CRM_2073_PACK,CRM_2074_PACK,CRM_2075_PACK,CRM_2131_PACK,CRM_2176_PACK,CRM_2181_PACK,CRM_2183_PACK,CRM_2187_PACK,CRM_2188_PACK,CRM_2191_PACK,CRM_2194_PACK,CRM_2196_PACK,CRM_2198_PACK,CRM_2199_PACK,CRM_2200_PACK,CRM_2203_PACK,CRM_2204_PACK,CRM_2206_PACK,CRM_2207_PACK,CRM_2208_PACK,CRM_2210_PACK,CRM_2213_PACK,CRM_2214_PACK,CRM_2216_PACK,CRM_2218_PACK,CRM_2221_PACK,CRM_2222_PACK,CRM_2223_PACK,CRM_2224_PACK,CRM_2225_PACK,CRM_2226_PACK,CRM_2228_PACK,CRM_2229_PACK,CRM_2230_PACK,CRM_2231_PACK,CRM_2234_PACK,CRM_2235_PACK,CRM_2236_PACK,CRM_2237_PACK,CRM_2238_PACK,CRM_2239_PACK,CRM_2240_PACK,CRM_2241_PACK,CRM_2242_PACK,CRM_2243_PACK,CRM_2244_PACK,CRM_2245_PACK,CRM_2246_PACK,CRM_2247_PACK,CRM_2248_PACK,CRM_2249_PACK,CRM_2250_PACK,CRM_2251_PACK,CRM_2253_PACK,CRM_2254_PACK,CRM_2256_PACK,CRM_2257_PACK,CRM_2259_PACK,CRM_2262_PACK,CRM_2263_PACK,CRM_2265_PACK,CRM_2267_PACK,CRM_2271_PACK,CRM_2276_PACK,CRM_2283_PACK,CRM_2287_PACK,CRM_2290_PACK,CRM_2296_PACK,CRM_2299_PACK,CRM_2301_PACK,CRM_2302_PACK,CRM_2307_PACK,CRM_2309_PACK,CRM_2317_PACK,CRM_1632_PACK,CRM_1831_PACK,CRM_1839_PACK,CRM_1872_PACK,CRM_1882_PACK,CRM_1891_PACK,CRM_1897_PACK,CRM_1904_PACK,CRM_1910_PACK,CRM_1930_PACK,CRM_1931_PACK,CRM_1932_PACK,CRM_1951_PACK,CRM_1959_PACK,CRM_1968_PACK,CRM_1969_PACK,CRM_2062_PACK,CRM_2064_PACK,CRM_2065_PACK,CRM_2067_PACK,CRM_2164_PACK,CRM_2189_PACK,CRM_2209_PACK,CRM_2211_PACK,CRM_2215_PACK,CRM_2227_PACK,CRM_2232_PACK,CRM_2233_PACK,CRM_2252_PACK,CRM_2255_PACK,CRM_2258_PACK,CRM_2266_PACK,CRM_2268_PACK,CRM_2269_PACK,CRM_2270_PACK,CRM_2272_PACK,CRM_2273_PACK,CRM_2274_PACK,CRM_2275_PACK,CRM_2277_PACK,CRM_2278_PACK,CRM_2279_PACK,CRM_2280_PACK,CRM_2281_PACK,CRM_2282_PACK,CRM_2284_PACK,CRM_2285_PACK,CRM_2286_PACK,CRM_2288_PACK,CRM_2289_PACK,CRM_2291_PACK,CRM_2292_PACK,CRM_2293_PACK,CRM_2294_PACK,CRM_2297_PACK,CRM_2298_PACK,CRM_2300_PACK,CRM_2303_PACK,CRM_2304_PACK,CRM_2305_PACK,CRM_2306_PACK,CRM_2308_PACK,CRM_2311_PACK,CRM_2312_PACK,CRM_2313_PACK,CRM_2314_PACK,CRM_2315_PACK,CRM_2316_PACK,CRM_2319_PACK,CRM_2320_PACK,CRM_2321_PACK,CRM_2322_PACK,CRM_2323_PACK,CRM_2324_PACK,CRM_2325_PACK,CRM_2326_PACK,CRM_2327_PACK,CRM_2328_PACK,CRM_2329_PACK,CRM_2330_PACK,CRM_2331_PACK,CRM_2332_PACK,CRM_2333_PACK,CRM_2335_PACK,CRM_2336_PACK,CRM_2337_PACK,CRM_2338_PACK,CRM_2339_PACK,CRM_2340_PACK,CRM_2341_PACK,CRM_2342_PACK,CRM_2343_PACK,CRM_2344_PACK,CRM_2345_PACK,CRM_2346_PACK,CRM_2347_PACK,CRM_2348_PACK,CRM_2349_PACK,CRM_2351_PACK,CRM_2352_PACK,CRM_2353_PACK,CRM_2354_PACK,CRM_2355_PACK,CRM_2356_PACK,CRM_2357_PACK,CRM_2358_PACK,CRM_2359_PACK,CRM_2360_PACK,CRM_2361_PACK,CRM_2362_PACK,CRM_2363_PACK,CRM_2364_PACK,CRM_2365_PACK,CRM_2366_PACK,CRM_2367_PACK,CRM_2368_PACK,CRM_2369_PACK,CRM_2370_PACK,CRM_2371_PACK,CRM_2372_PACK,CRM_2373_PACK,CRM_2374_PACK,CRM_2375_PACK,CRM_2376_PACK,CRM_2377_PACK,CRM_2378_PACK,CRM_2379_PACK,CRM_2380_PACK,CRM_2381_PACK,CRM_2382_PACK,CRM_2383_PACK,CRM_2385_PACK,CRM_2387_PACK,CRM_2388_PACK,CRM_2389_PACK,CRM_2391_PACK,CRM_2392_PACK,CRM_2394_PACK,CRM_2395_PACK,CRM_2396_PACK,CRM_2397_PACK,CRM_2398_PACK,Bill_Conf,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730
0,db67b03cf9fb8ea96077cd34c7a28139,1,0,1,1,1,0,0,1,1,1,1,0,1,1,0,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000000000000000000000000000000000000000000000...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,0,0,1,0,1,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2ac0d310d5cf1a96587af614d37b8b54,1,0,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1000000000100000000000000000000100000000000000...,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [9]:
test = test.drop(columns=['Bill_Conf'])

In [10]:
columns_to_rename = [c for c in test.columns if c not in CRM_COLS and c != ID_COL]

In [11]:
rename_dict = dict(zip(columns_to_rename, BIL_COLS))

test = test.rename(columns=rename_dict)

In [12]:
#2. Define X and Y

X = train[CRM_COLS].astype(np.uint8)
Y = train[BIL_COLS].astype(np.uint8)

X_test = test[CRM_COLS].astype(np.uint8)
Y_test = test[BIL_COLS].astype(np.uint8)

# Convert only the arrays used for calculations to int64.
# This prevents integer overflow when counting observations.
X_np = X.to_numpy(dtype=np.int64)
Y_np = Y.to_numpy(dtype=np.int64)

In [13]:
# 3. Binary Mutual Information Filter

MI_TOP_K = 25

n_samples = X_np.shape[0]
n_crm = X_np.shape[1]
n_bil = Y_np.shape[1]

selected_features = {}

# Number of 1s and 0s for every CRM variable
x_ones = X_np.sum(axis=0)
x_zeros = n_samples - x_ones

for j in range(n_bil):

    y = Y_np[:, j]

    y_ones = y.sum()
    y_zeros = n_samples - y_ones

    # Count CRM=1 AND Billing=1 for every CRM variable
    xy_11 = X_np.T @ y

    # Remaining cells of each 2x2 contingency table
    xy_10 = x_ones - xy_11
    xy_01 = y_ones - xy_11
    xy_00 = n_samples - xy_11 - xy_10 - xy_01

    # Expected counts under independence
    expected_11 = (x_ones * y_ones) / n_samples
    expected_10 = (x_ones * y_zeros) / n_samples
    expected_01 = (x_zeros * y_ones) / n_samples
    expected_00 = (x_zeros * y_zeros) / n_samples

    # Exact binary mutual information
    mi = np.zeros(n_crm, dtype=np.float64)

    cells = [
        (xy_11, expected_11),
        (xy_10, expected_10),
        (xy_01, expected_01),
        (xy_00, expected_00)
    ]

    for observed, expected in cells:

        valid = observed > 0

        mi[valid] += (
            observed[valid] / n_samples
        ) * np.log(
            observed[valid] / expected[valid]
        )

    # Keep only the top CRM variables
    k = min(MI_TOP_K, n_crm)

    top_idx = np.argpartition(
        mi,
        -k
    )[-k:]

    top_idx = top_idx[
        np.argsort(mi[top_idx])[::-1]
    ]

    selected_features[BIL_COLS[j]] = [
        CRM_COLS[idx]
        for idx in top_idx
    ]

    if (j + 1) % 50 == 0:
        print(f"MI progress: {j + 1}/{n_bil}")

# Filter summary

print(
    f"\nMI filter completed: "
    f"{n_bil} Billing targets × {n_crm} CRM features"
)

print(
    f"CRM features retained per Billing target: {MI_TOP_K}"
)

MI progress: 50/731
MI progress: 100/731
MI progress: 150/731
MI progress: 200/731
MI progress: 250/731
MI progress: 300/731
MI progress: 350/731
MI progress: 400/731
MI progress: 450/731
MI progress: 500/731
MI progress: 550/731
MI progress: 600/731
MI progress: 650/731
MI progress: 700/731

MI filter completed: 731 Billing targets × 745 CRM features
CRM features retained per Billing target: 25

In [14]:
#4. Wrapper

WRAPPER_TOP_K = 10

for i, bil_col in enumerate(BIL_COLS):

    features = selected_features[bil_col]
    y = Y[bil_col].values

    if len(features) > WRAPPER_TOP_K and np.unique(y).size > 1:

        model = LogisticRegression(
            solver="liblinear",
            max_iter=100,
            random_state=42
        )

        model.fit(
            X[features],
            y
        )

        # Rank the MI-selected features by model importance
        importance = np.abs(model.coef_[0])

        top_idx = np.argsort(
            importance
        )[-WRAPPER_TOP_K:]

        selected_features[bil_col] = [
            features[idx]
            for idx in top_idx
        ]

    if (i + 1) % 50 == 0:
        print(f"Wrapper progress: {i + 1}/{n_bil}")

Wrapper progress: 50/731
Wrapper progress: 100/731
Wrapper progress: 150/731
Wrapper progress: 200/731
Wrapper progress: 250/731
Wrapper progress: 300/731
Wrapper progress: 350/731
Wrapper progress: 400/731
Wrapper progress: 450/731
Wrapper progress: 500/731
Wrapper progress: 550/731
Wrapper progress: 600/731
Wrapper progress: 650/731
Wrapper progress: 700/731

In [15]:
#5. One vs All model

models = {}

for i, bil_col in enumerate(BIL_COLS):

    features = selected_features[bil_col]
    y = Y[bil_col].values

    if np.unique(y).size < 2:

        models[bil_col] = None

    else:

        model = LogisticRegression(
            solver="liblinear",
            max_iter=200,
            random_state=42
        )

        model.fit(
            X[features],
            y
        )

        models[bil_col] = model

    if (i + 1) % 50 == 0:
        print(f"Model progress: {i + 1}/{n_bil}")

Model progress: 50/731
Model progress: 100/731
Model progress: 150/731
Model progress: 200/731
Model progress: 250/731
Model progress: 300/731
Model progress: 350/731
Model progress: 400/731
Model progress: 450/731
Model progress: 500/731
Model progress: 550/731
Model progress: 600/731
Model progress: 650/731
Model progress: 700/731

In [16]:
#6. Prediction

Y_pred = np.zeros(
    (len(X_test), len(BIL_COLS)),
    dtype=np.uint8
)

for j, bil_col in enumerate(BIL_COLS):

    model = models[bil_col]
    features = selected_features[bil_col]

    if model is None:

        Y_pred[:, j] = Y[bil_col].iloc[0]

    else:

        Y_pred[:, j] = model.predict(
            X_test[features]
        ).astype(np.uint8)


Y_pred = pd.DataFrame(
    Y_pred,
    columns=BIL_COLS,
    index=test.index
)

In [17]:
#7. Exact Match Ratio

exact_matches = (
    Y_pred.values == Y_test.values
).all(axis=1)

EMR = exact_matches.mean()

print("\n==============================")
print(f"Exact Matching Ratio: {EMR:.6f}")
print(
    f"Correct samples: "
    f"{exact_matches.sum()}/{len(exact_matches)}"
)
print("==============================")

==============================
Exact Matching Ratio: 0.879166
Correct samples: 85367/97100
==============================

In [18]:
#8. SAVE PREDICTIONS

prediction = pd.concat([test[[ID_COL]], Y_pred], axis=1)

prediction.to_csv("billing_predictions.csv", index=False)